spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.username=root
spring.datasource.password=Vinayak@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=nskfksdk21897@873dnasndakjdskakbdkjbakbsdkj98743298#1
jwt.expiration=86400000